<?php

if (!function_exists('getSiteName')) {
  function getSiteName()
  {
    return 'monstercall.com';
  }
}

if (!function_exists('getSiteEmail')) {
  function getSiteEmail()
  {
    return 'info@monstercall@com';
  }
}

if (!function_exists('getSitePhone')) {
  function getSitePhone()
  {
    return '+1 480 666 8310';
  }
}

if (!function_exists('getMonths')) {
  function getMonths()
  {
    return array (
      ''  => 'Months',
      '01' => 'JAN',
      '02'  => 'FEB',
      '03'  => 'MAR',
      '04'  => 'APR',
      '05'  => 'MAY',
      '06'  => 'JUN',
      '07' => 'JUL',
      '08' => 'AUG',
      '09' => 'SEP',
      '10' => 'OCT',
      '11' => 'NOV',
      '12' => 'DEC',
    );
  }
}

if (!function_exists('getCountries')) {
  function getCountries()
  {
    return array (
        '' => 'Choose Country',
        'AF' => 'Afghanistan',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AS' => 'American Samoa',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguilla',
        'AQ' => 'Antarctica',
        'AG' => 'Antigua and Barbuda',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AW' => 'Aruba',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BS' => 'Bahamas',
        'BH' => 'Bahrain',
        'BD' => 'Bangladesh',
        'BB' => 'Barbados',
        'BY' => 'Belarus',
        'BE' => 'Belgium',
        'BZ' => 'Belize',
        'BJ' => 'Benin',
        'BM' => 'Bermuda',
        'BT' => 'Bhutan',
        'BO' => 'Bolivia',
        'BQ' => 'Bonaire, Sint Eustatius and Saba',
        'BA' => 'Bosnia and Herzegovina',
        'BW' => 'Botswana',
        'BV' => 'Bouvet Island',
        'BR' => 'Brazil',
        'IO' => 'British Indian Ocean Territory',
        'BN' => 'Brunei Darussalam',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'KH' => 'Cambodia',
        'CM' => 'Cameroon',
        'CA' => 'Canada',
        'CV' => 'Cape Verde',
        'KY' => 'Cayman Islands',
        'CF' => 'Central African Republic',
        'TD' => 'Chad',
        'CL' => 'Chile',
        'CN' => 'China',
        'CX' => 'Christmas Island',
        'CC' => 'Cocos (Keeling) Islands',
        'CO' => 'Colombia',
        'KM' => 'Comoros',
        'CG' => 'Congo',
        'CD' => 'Congo, The Democratic Republic Of The',
        'CK' => 'Cook Islands',
        'CR' => 'Costa Rica',
        'HR' => 'Croatia',
        'CU' => 'Cuba',
        'CW' => 'Curaçao',
        'CY' => 'Cyprus',
        'CZ' => 'Czech Republic',
        'CI' => 'Côte D\'Ivoire',
        'DK' => 'Denmark',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'EC' => 'Ecuador',
        'EG' => 'Egypt',
        'SV' => 'El Salvador',
        'GQ' => 'Equatorial Guinea',
        'ER' => 'Eritrea',
        'EE' => 'Estonia',
        'ET' => 'Ethiopia',
        'FK' => 'Falkland Islands (Malvinas)',
        'FO' => 'Faroe Islands',
        'FJ' => 'Fiji',
        'FI' => 'Finland',
        'FR' => 'France',
        'GF' => 'French Guiana',
        'PF' => 'French Polynesia',
        'TF' => 'French Southern Territories',
        'GA' => 'Gabon',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'DE' => 'Germany',
        'GH' => 'Ghana',
        'GI' => 'Gibraltar',
        'GR' => 'Greece',
        'GL' => 'Greenland',
        'GD' => 'Grenada',
        'GP' => 'Guadeloupe',
        'GU' => 'Guam',
        'GT' => 'Guatemala',
        'GG' => 'Guernsey',
        'GN' => 'Guinea',
        'GW' => 'Guinea-Bissau',
        'GY' => 'Guyana',
        'HT' => 'Haiti',
        'HM' => 'Heard and McDonald Islands',
        'VA' => 'Holy See (Vatican City State)',
        'HN' => 'Honduras',
        'HK' => 'Hong Kong',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IR' => 'Iran, Islamic Republic Of',
        'IQ' => 'Iraq',
        'IE' => 'Ireland',
        'IM' => 'Isle of Man',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'JM' => 'Jamaica',
        'JP' => 'Japan',
        'JE' => 'Jersey',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KE' => 'Kenya',
        'KI' => 'Kiribati',
        'KP' => 'Korea, Democratic People\'s Republic Of',
        'KR' => 'Korea, Republic of',
        'KW' => 'Kuwait',
        'KG' => 'Kyrgyzstan',
        'LA' => 'Lao People\'s Democratic Republic',
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LS' => 'Lesotho',
        'LR' => 'Liberia',
        'LY' => 'Libya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MO' => 'Macao',
        'MK' => 'Macedonia, the Former Yugoslav Republic Of',
        'MG' => 'Madagascar',
        'MW' => 'Malawi',
        'MY' => 'Malaysia',
        'MV' => 'Maldives',
        'ML' => 'Mali',
        'MT' => 'Malta',
        'MH' => 'Marshall Islands',
        'MQ' => 'Martinique',
        'MR' => 'Mauritania',
        'MU' => 'Mauritius',
        'YT' => 'Mayotte',
        'MX' => 'Mexico',
        'FM' => 'Micronesia, Federated States Of',
        'MD' => 'Moldova, Republic of',
        'MC' => 'Monaco',
        'MN' => 'Mongolia',
        'ME' => 'Montenegro',
        'MS' => 'Montserrat',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'MM' => 'Myanmar',
        'NA' => 'Namibia',
        'NR' => 'Nauru',
        'NP' => 'Nepal',
        'NL' => 'Netherlands',
        'AN' => 'Netherlands Antilles',
        'NC' => 'New Caledonia',
        'NZ' => 'New Zealand',
        'NI' => 'Nicaragua',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'NU' => 'Niue',
        'NF' => 'Norfolk Island',
        'MP' => 'Northern Mariana Islands',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PW' => 'Palau',
        'PS' => 'Palestine, State of',
        'PA' => 'Panama',
        'PG' => 'Papua New Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Peru',
        'PH' => 'Philippines',
        'PN' => 'Pitcairn',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'PR' => 'Puerto Rico',
        'QA' => 'Qatar',
        'RO' => 'Romania',
        'RU' => 'Russian Federation',
        'RW' => 'Rwanda',
        'RE' => 'Réunion',
        'BL' => 'Saint Barthélemy',
        'SH' => 'Saint Helena',
        'KN' => 'Saint Kitts And Nevis',
        'LC' => 'Saint Lucia',
        'MF' => 'Saint Martin',
        'PM' => 'Saint Pierre And Miquelon',
        'VC' => 'Saint Vincent And The Grenedines',
        'WS' => 'Samoa',
        'SM' => 'San Marino',
        'ST' => 'Sao Tome and Principe',
        'SA' => 'Saudi Arabia',
        'SN' => 'Senegal',
        'RS' => 'Serbia',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SG' => 'Singapore',
        'SX' => 'Sint Maarten',
        'SK' => 'Slovakia',
        'SI' => 'Slovenia',
        'SB' => 'Solomon Islands',
        'SO' => 'Somalia',
        'ZA' => 'South Africa',
        'GS' => 'South Georgia and the South Sandwich Islands',
        'SS' => 'South Sudan',
        'ES' => 'Spain',
        'LK' => 'Sri Lanka',
        'SD' => 'Sudan',
        'SR' => 'Suriname',
        'SJ' => 'Svalbard And Jan Mayen',
        'SZ' => 'Swaziland',
        'SE' => 'Sweden',
        'CH' => 'Switzerland',
        'SY' => 'Syrian Arab Republic',
        'TW' => 'Taiwan, Republic Of China',
        'TJ' => 'Tajikistan',
        'TZ' => 'Tanzania, United Republic of',
        'TH' => 'Thailand',
        'TL' => 'Timor-Leste',
        'TG' => 'Togo',
        'TK' => 'Tokelau',
        'TO' => 'Tonga',
        'TT' => 'Trinidad and Tobago',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TM' => 'Turkmenistan',
        'TC' => 'Turks and Caicos Islands',
        'TV' => 'Tuvalu',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'GB' => 'United Kingdom',
        'US' => 'United States',
        'UM' => 'United States Minor Outlying Islands',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VU' => 'Vanuatu',
        'VE' => 'Venezuela, Bolivarian Republic of',
        'VN' => 'Vietnam',
        'VG' => 'Virgin Islands, British',
        'VI' => 'Virgin Islands, U.S.',
        'WF' => 'Wallis and Futuna',
        'EH' => 'Western Sahara',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe',
        'AX' => 'Åland Islands',
      );
  }
}

if (!function_exists('getYears')) {
  function getYears($startsFrom = '', $next=10)
  {
    date_default_timezone_set(env('APP_TIMEZONE', 'UTC'));
    $startsFrom = ($startsFrom == '') ? date('Y') : $startsFrom;
    //$yearRange  = range($startsFrom, $startsFrom + $next);
    $years  = array();
    for ($i=$startsFrom; $i <= $startsFrom + $next; $i++) {
      $years[$i]  = intval($i);
    }
    return $years;
  }
}

$monsterCall                       = array();
$monsterCall['site_name']          = getSiteName();
$monsterCall['site_email']         = getSiteEmail();
$monsterCall['site_phone']         = getSitePhone();
$monsterCall['months']             = getMonths();
$monsterCall['years']              = getYears();
$monsterCall['countries']          = getCountries();
$monsterCall['site_fb_link']       = '#';
$monsterCall['site_twitter_link']  = '#';
$monsterCall['site_linkedin_link'] = '#';
$monsterCall['site_gplus_link']    = '#';

$monsterCall['linkedin_auth_callback']  = env('LINKEDIN_AUTH_CALLBACK', 'http://dev.monstercall.preptest.in/authenticate/linkedin/callback');

$monsterCall['facebook_verification_callback']  = env('FACEBOOK_VERIFICATION_CALLBACK', 'http://dev.monstercall.preptest.in/verification/facebook/callback');
$monsterCall['linkedin_verification_callback']  = env('LINKEDIN_VERIFICATION_CALLBACK', 'http://dev.monstercall.preptest.in/verification/linkedin/callback');
$monsterCall['twitter_verification_callback']  = env('TWITTER_VERIFICATION_CALLBACK', 'http://dev.monstercall.preptest.in/verification/twitter/callback');

$monsterCall['timezones']  = array(
    ''                             => 'Select a timezone',
    'Hawaii'                       => '(GMT-10:00) Hawaii',
    'Alaska'                       => '(GMT-08:00) Alaska',
    'Pacific Time (US & Canada)'   => '(GMT-07:00) Pacific Time (US & Canada)',
    'Arizona'                      => '(GMT-07:00) Arizona',
    'Mountain Time (US & Canada)'  => '(GMT-06:00) Mountain Time (US & Canada)',
    'Central Time (US & Canada)'   => '(GMT-05:00) Central Time (US & Canada)',
    'Eastern Time (US & Canada)'   => '(GMT-04:00) Eastern Time (US & Canada)',
    'Indiana (East)'               => '(GMT-04:00) Indiana (East)',
    'Atlantic Time (Canada)'       => '(GMT-03:00) Atlantic Time (Canada)',
    'American Samoa'               => '(GMT-11:00) American Samoa',
    'International Date Line West' => '(GMT-11:00) International Date Line West',
    'Midway Island'                => '(GMT-11:00) Midway Island',
    'Tijuana'                      => '(GMT-07:00) Tijuana',
    'Chihuahua'                    => '(GMT-06:00) Chihuahua',
    'Mazatlan'                     => '(GMT-06:00) Mazatlan',
    'Central America'              => '(GMT-06:00) Central America',
    'Guadalajara'                  => '(GMT-05:00) Guadalajara',
    'Mexico City'                  => '(GMT-05:00) Mexico City',
    'Monterrey'                    => '(GMT-05:00) Monterrey',
    'Saskatchewan'                 => '(GMT-06:00) Saskatchewan',
    'Bogota'                       => '(GMT-05:00) Bogota',
    'Lima'                         => '(GMT-05:00) Lima',
    'Quito'                        => '(GMT-05:00) Quito',
    'Caracas'                      => '(GMT-04:30) Caracas',
    'Georgetown'                   => '(GMT-04:00) Georgetown',
    'La Paz'                       => '(GMT-04:00) La Paz',
    'Newfoundland'                 => '(GMT-02:30) Newfoundland',
    'Brasilia'                     => '(GMT-03:00) Brasilia',
    'Buenos Aires'                 => '(GMT-03:00) Buenos Aires',
    'Greenland'                    => '(GMT-02:00) Greenland',
    'Santiago'                     => '(GMT-03:00) Santiago',
    'Mid-Atlantic'                 => '(GMT-02:00) Mid-Atlantic',
    'Azores'                       => '(GMT+00:00) Azores',
    'Cape Verde Is.'               => '(GMT-01:00) Cape Verde Is.',
    'Casablanca'                   => '(GMT+00:00) Casablanca',
    'Dublin'                       => '(GMT+01:00) Dublin',
    'Edinburgh'                    => '(GMT+01:00) Edinburgh',
    'Lisbon'                       => '(GMT+01:00) Lisbon',
    'London'                       => '(GMT+01:00) London',
    'Monrovia'                     => '(GMT+00:00) Monrovia',
    'UTC'                          => '(GMT+00:00) UTC',
    'Amsterdam'                    => '(GMT+02:00) Amsterdam',
    'Belgrade'                     => '(GMT+02:00) Belgrade',
    'Berlin'                       => '(GMT+02:00) Berlin',
    'Bern'                         => '(GMT+02:00) Bern',
    'Bratislava'                   => '(GMT+02:00) Bratislava',
    'Brussels'                     => '(GMT+02:00) Brussels',
    'Budapest'                     => '(GMT+02:00) Budapest',
    'Copenhagen'                   => '(GMT+02:00) Copenhagen',
    'Ljubljana'                    => '(GMT+02:00) Ljubljana',
    'Madrid'                       => '(GMT+02:00) Madrid',
    'Paris'                        => '(GMT+02:00) Paris',
    'Prague'                       => '(GMT+02:00) Prague',
    'Rome'                         => '(GMT+02:00) Rome',
    'Sarajevo'                     => '(GMT+02:00) Sarajevo',
    'Skopje'                       => '(GMT+02:00) Skopje',
    'Stockholm'                    => '(GMT+02:00) Stockholm',
    'Vienna'                       => '(GMT+02:00) Vienna',
    'Warsaw'                       => '(GMT+02:00) Warsaw',
    'West Central Africa'          => '(GMT+01:00) West Central Africa',
    'Zagreb'                       => '(GMT+02:00) Zagreb',
    'Athens'                       => '(GMT+03:00) Athens',
    'Bucharest'                    => '(GMT+03:00) Bucharest',
    'Cairo'                        => '(GMT+02:00) Cairo',
    'Harare'                       => '(GMT+02:00) Harare',
    'Helsinki'                     => '(GMT+03:00) Helsinki',
    'Istanbul'                     => '(GMT+03:00) Istanbul',
    'Jerusalem'                    => '(GMT+03:00) Jerusalem',
    'Kyiv'                         => '(GMT+03:00) Kyiv',
    'Pretoria'                     => '(GMT+02:00) Pretoria',
    'Riga'                         => '(GMT+03:00) Riga',
    'Sofia'                        => '(GMT+03:00) Sofia',
    'Tallinn'                      => '(GMT+03:00) Tallinn',
    'Vilnius'                      => '(GMT+03:00) Vilnius',
    'Baghdad'                      => '(GMT+03:00) Baghdad',
    'Kuwait'                       => '(GMT+03:00) Kuwait',
    'Minsk'                        => '(GMT+03:00) Minsk',
    'Moscow'                       => '(GMT+03:00) Moscow',
    'Nairobi'                      => '(GMT+03:00) Nairobi',
    'Riyadh'                       => '(GMT+03:00) Riyadh',
    'St. Petersburg'               => '(GMT+03:00) St. Petersburg',
    'Volgograd'                    => '(GMT+03:00) Volgograd',
    'Tehran'                       => '(GMT+04:30) Tehran',
    'Abu Dhabi'                    => '(GMT+04:00) Abu Dhabi',
    'Baku'                         => '(GMT+05:00) Baku',
    'Muscat'                       => '(GMT+04:00) Muscat',
    'Tbilisi'                      => '(GMT+04:00) Tbilisi',
    'Yerevan'                      => '(GMT+04:00) Yerevan',
    'Kabul'                        => '(GMT+04:30) Kabul',
    'Ekaterinburg'                 => '(GMT+05:00) Ekaterinburg',
    'Islamabad'                    => '(GMT+05:00) Islamabad',
    'Karachi'                      => '(GMT+05:00) Karachi',
    'Tashkent'                     => '(GMT+05:00) Tashkent',
    'Chennai'                      => '(GMT+05:30) Chennai',
    'Kolkata'                      => '(GMT+05:30) Kolkata',
    'Mumbai'                       => '(GMT+05:30) Mumbai',
    'New Delhi'                    => '(GMT+05:30) New Delhi',
    'Sri Jayawardenepura'          => '(GMT+05:30) Sri Jayawardenepura',
    'Kathmandu'                    => '(GMT+05:45) Kathmandu',
    'Almaty'                       => '(GMT+06:00) Almaty',
    'Astana'                       => '(GMT+06:00) Astana',
    'Dhaka'                        => '(GMT+06:00) Dhaka',
    'Novosibirsk'                  => '(GMT+06:00) Novosibirsk',
    'Urumqi'                       => '(GMT+06:00) Urumqi',
    'Rangoon'                      => '(GMT+06:30) Rangoon',
    'Bangkok'                      => '(GMT+07:00) Bangkok',
    'Hanoi'                        => '(GMT+07:00) Hanoi',
    'Jakarta'                      => '(GMT+07:00) Jakarta',
    'Krasnoyarsk'                  => '(GMT+07:00) Krasnoyarsk',
    'Beijing'                      => '(GMT+08:00) Beijing',
    'Chongqing'                    => '(GMT+08:00) Chongqing',
    'Hong Kong'                    => '(GMT+08:00) Hong Kong',
    'Irkutsk'                      => '(GMT+08:00) Irkutsk',
    'Kuala Lumpur'                 => '(GMT+08:00) Kuala Lumpur',
    'Perth'                        => '(GMT+08:00) Perth',
    'Singapore'                    => '(GMT+08:00) Singapore',
    'Taipei'                       => '(GMT+08:00) Taipei',
    'Ulaan Bataar'                 => '(GMT+09:00) Ulaan Bataar',
    'Osaka'                        => '(GMT+09:00) Osaka',
    'Sapporo'                      => '(GMT+09:00) Sapporo',
    'Seoul'                        => '(GMT+09:00) Seoul',
    'Tokyo'                        => '(GMT+09:00) Tokyo',
    'Yakutsk'                      => '(GMT+09:00) Yakutsk',
    'Adelaide'                     => '(GMT+09:30) Adelaide',
    'Darwin'                       => '(GMT+09:30) Darwin',
    'Brisbane'                     => '(GMT+10:00) Brisbane',
    'Canberra'                     => '(GMT+10:00) Canberra',
    'Guam'                         => '(GMT+10:00) Guam',
    'Hobart'                       => '(GMT+10:00) Hobart',
    'Magadan'                      => '(GMT+10:00) Magadan',
    'Melbourne'                    => '(GMT+10:00) Melbourne',
    'Port Moresby'                 => '(GMT+10:00) Port Moresby',
    'Solomon Is.'                  => '(GMT+10:00) Solomon Is.',
    'Sydney'                       => '(GMT+10:00) Sydney',
   'Vladivostok'                   => '(GMT+10:00) Vladivostok',
   'New Caledonia'                 => '(GMT+11:00) New Caledonia',
   'Auckland'                      => '(GMT+12:00) Auckland',
   'Fiji'                          => '(GMT+12:00) Fiji',
   'Kamchatka'                     => '(GMT+12:00) Kamchatka',
   'Marshall Is.'                  => '(GMT+12:00) Marshall Is.',
   'Wellington'                    => '(GMT+12:00) Wellington',
   'Nuku'                          => '(GMT+13:00) Nuku',
    'Samoa'                        => '(GMT+13:00) Samoa',
    'Tokelau Is.'                  => '(GMT+13:00) Tokelau Is.'
  );

  $monsterCall['hourlyRates']          = array(
      ''  => 'Select an hourly rate',
      0   => '$0',
      60  => '$60',
      100 => '$100',
      120 => '$120',
      150 => '$150',
      175 => '$175',
      200 => '$200'
  );

  $monsterCall['callLength']          = array(
      ''  => 'Select a call length',
      15  => '15 minutes',
      30  => '30 minutes',
      1   => '1 hour',
      2   => '2 hours'
  );

  $monsterCall['callTime']          = array(
      '' => '12:00 AM',
      '1:00 AM' => '1:00 AM',
      '2:00 AM' => '2:00 AM',
      '3:00 AM' => '3:00 AM',
      '4:00 AM' => '4:00 AM',
      '5:00 AM' => '5:00 AM',
      '6:00 AM' => '6:00 AM',
      '7:00 AM' => '7:00 AM',
      '8:00 AM' => '8:00 AM',
      '9:00 AM' => '9:00 AM',
      '10:00 AM' => '10:00 AM',
      '11:00 AM' => '11:00 AM',
      '12:00 PM' => '12:00 PM',
      '1:00 PM' => '13:00 PM',
      '2:00 PM' => '14:00 PM',
      '3:00 PM' => '15:00 PM',
      '4:00 PM' => '16:00 PM',
      '5:00 PM' => '17:00 PM',
      '6:00 PM' => '18:00 PM',
      '7:00 PM' => '19:00 PM',
      '8:00 PM' => '20:00 PM',
      '9:00 PM' => '21:00 PM',
      '10:00 PM' => '22:00 PM',
      '11:00 PM' => '23:00 PM'
    );

  $monsterCall['rating']          = array(
      ''  => 'Please Rate Your Call Experience',
      1  => '1',
      2  => '2',
      3  => '3',
      4  => '4',
      5  => '5'
  );

  $monsterCall['cacheStoringTime']          = 60 * 24; // 1hour * 24;
  $monsterCall['questions_per_page']    = 10;
  $monsterCall['expertises_per_page']    = 10;

return $monsterCall;
